name: Publish
on: [workflow_dispatch]
jobs:
  # publishing azure artifacts
  azure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install --global vsce
      - run: vsce package
      - run: vsce publish -p ${{ secrets.PAT }}